name: Cleanup All Workflow Runs

on:
  workflow_dispatch:  # Запуск вручную
  schedule:
     - cron: '0 1 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0           # Не хранить ничего
          keep_minimum_runs: 0     # Не сохранять даже последние
